#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 12 11:26:26 2017

@author: evelyn
"""

'''
Given numRows, generate the first numRows of Pascal's triangle.

For example, given numRows = 5,
Return

[
     [1],
    [1,1],
   [1,2,1],
  [1,3,3,1],
 [1,4,6,4,1]
]

'''
def generate(numRows):
    """
    :type numRows: int
    :rtype: List[List[int]]
    """
    if numRows == 0:
        return []
    if numRows == 1:
        return [[1]]
    if numRows == 2:
        return [[1],[1,1]]
    
    last = generate(numRows - 1)
    lastOne = last[-1]
    
    ans = []
    ans.append(1)
    for i in range(len(lastOne) - 1):
        ans.append(lastOne[i] + lastOne[i+1])
    
    ans.append(1)
    last.append(ans)
    
    return last
        
    
