#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 14 23:18:42 2017

@author: evelyn
"""

'''
Say you have an array for which the ith element is the price of a given 
stock on day i.

Design an algorithm to find the maximum profit. You may complete as many 
transactions as you like (ie, buy one and sell one share of the stock 
multiple times). However, you may not engage in multiple transactions 
at the same time (ie, you must sell the stock before you buy again).
'''
def maxProfit(prices):
    """
    :type prices: List[int]
    :rtype: int
    """
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 15 12:31:12 2017

@author: evelyn
"""

'''
Say you have an array for which the ith element is the price of a given 
stock on day i.

Design an algorithm to find the maximum profit. You may complete as many 
transactions as you like (ie, buy one and sell one share of the stock 
multiple times). However, you may not engage in multiple transactions 
at the same time (ie, you must sell the stock before you buy again).
'''
def maxProfit(prices):
    """
    :type prices: List[int]
    :rtype: int
    """
    return sum(y-x for x,y in zip(prices[:-1], prices[1:]) if y > x)
