#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 11 09:18:54 2017

@author: evelyn
"""

'''
Given an array of integers that is already sorted in ascending order, 
find two numbers such that they add up to a specific target number.

The function twoSum should return indices of the two numbers such that 
they add up to the target, where index1 must be less than index2. 
Please note that your returned answers (both index1 and index2) a
re not zero-based.

You may assume that each input would have exactly one solution and 
you may not use the same element twice.

Input: numbers={2, 7, 11, 15}, target=9
Output: index1=1, index2=2 
'''

def twoSum(numbers, target):
    """
    :type numbers: List[int]
    :type target: int
    :rtype: List[int]
    """
    n = len(numbers)
    map = {}
    for i in range(n):
        if numbers[i] not in map:
            if target - numbers[i] <= numbers[n-1]:
                map[target - numbers[i]] = i
        else:
            x = min(i, map[numbers[i]])
            y = max(i, map[numbers[i]])
            if x != y:
                return x+1,y+1
