#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 11 09:55:05 2017

@author: evelyn
"""

'''
Given an array of size n, find the majority element. 
The majority element is the element that appears more than ⌊ n/2 ⌋ times.

You may assume that the array is non-empty and the majority element 
always exist in the array.
'''
def majorityElement(nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    map = {}
    
    n = len(nums)
    if n == 1:
        return nums[0]
    for i in range(n):
        if nums[i] not in map:
            map[nums[i]] = 1
        else:
            map[nums[i]] += 1
            if map[nums[i]] > n/2:
                return nums[i]
            
