#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 13 16:53:17 2017

@author: evelyn
"""

'''
Rotate an array of n elements to the right by k steps.

For example, with n = 7 and k = 3, the array [1,2,3,4,5,6,7] is 
rotated to [5,6,7,1,2,3,4]. 
'''
def rotate(nums, k):
    """
    :type nums: List[int]
    :type k: int
    :rtype: void Do not return anything, modify nums in-place instead.
    """
    n = len(nums)
    
    if n >= 2:
        p = k%n
        tmp = []
        tmp[:] = nums[n-p:]
        nums[n-p-1:] = nums[:n-p]
        nums[:n-p-1] = tmp[:]
