#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 11 10:27:13 2017

@author: evelyn
"""

'''
Given an array of integers, find if the array contains any duplicates. 
Your function should return true if any value appears at least twice 
in the array, and it should return false if every element is distinct. 
'''

def containsDuplicate(nums):
    """
    :type nums: List[int]
    :rtype: bool
    """
    n = len(nums)
    
    if n < 2:
        return False
    else:
        map = {}
        for i in range(n):
            if nums[i] not in map:
                map[nums[i]] = 1
            else:
                return True
    return False
    
