#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 12 21:21:13 2017

@author: evelyn
"""

'''
Given an array of integers and an integer k, find out whether there are 
two distinct indices i and j in the array such that nums[i] = nums[j] and 
the absolute difference between i and j is at most k. 
'''
def containsNearbyDuplicate(nums, k):
    """
    :type nums: List[int]
    :type k: int
    :rtype: bool
    """
    n = len(nums)
    if n == 0:
        return False
    
    dic = {}
    for i in range(n):
        print "i = " + str(i)
        print "nums[i] = " + str(nums[i])
        print "dic is "+ str(dic)
        if nums[i] not in dic:
            dic[nums[i]] = i
        else:
            if i != dic[nums[i]] and abs(i - dic[nums[i]]) <= k:
                return True
            else:
                dic[nums[i]] = i
    return False
