#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 10 11:41:10 2017

@author: evelyn
"""

'''
 Given an array nums, write a function to move all 0's to the end of it while maintaining the relative order of the non-zero elements.

For example, given nums = [0, 1, 0, 3, 12], after calling your function, nums should be [1, 3, 12, 0, 0].

Note:

    You must do this in-place without making a copy of the array.
    Minimize the total number of operations.

'''
def moveZeroes(nums):
    """
    :type nums: List[int]
    :rtype: void Do not return anything, modify nums in-place instead.
    """
    counter = 0
    for item in nums:
        if item == 0:
            counter += 1
    nums[:] = [x for x in nums if x != 0]
    print "nums is now " + str(nums)
    
    #nums += [0]*counter
    nums.extend([0]*counter)
    
    print "nums is now " + str(nums)
    
