#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 10 11:41:10 2017

@author: evelyn
"""

'''
 Given an array nums, write a function to move all 0's to the end of it while maintaining the relative order of the non-zero elements.

For example, given nums = [0, 1, 0, 3, 12], after calling your function, nums should be [1, 3, 12, 0, 0].

Note:

    You must do this in-place without making a copy of the array.
    Minimize the total number of operations.

'''
def moveZeroes(nums):
    """
    :type nums: List[int]
    :rtype: void Do not return anything, modify nums in-place instead.
    """
    if len(nums) != 0:
        for i in range(len(nums)):
	    if nums[i] == 0:
	        nums[i] = ‘’
		nums.append(0)
	while ‘’ in nums:
	    nums.remove(‘’)


