#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 11 17:27:59 2017

@author: evelyn
"""

'''
Given a sorted array and a target value, return the index if the target is 
found. If not, return the index where it would be if it were inserted in 
order.

You may assume no duplicates in the array.

Here are few examples.
[1,3,5,6], 5 → 2
[1,3,5,6], 2 → 1
[1,3,5,6], 7 → 4
[1,3,5,6], 0 → 0 
'''
def searchInsert(nums, target):
    """
    :type nums: List[int]
    :type target: int
    :rtype: int
    """
    n = len(nums)
    if nums[0] >= target:
        return 0
    if nums[n-1] < target:
        return n
    if nums[n-1] == target:
        return n-1
    for i in range(1,n):
        if nums[i] == target:
            return i
        elif nums[i] > target and nums[i - 1] < target:
            return i
