#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 13 20:04:40 2017

@author: evelyn
"""
'''
Given an array of integers, 1 ≤ a[i] ≤ n (n = size of array), some 
elements appear twice and others appear once.

Find all the elements that appear twice in this array.

Could you do it without extra space and in O(n) runtime?

Example:

Input:
[4,3,2,7,8,2,3,1]

Output:
[2,3]

'''
def findDuplicates(nums):
    """
    :type nums: List[int]
    :rtype: List[int]
    """
    n = len(nums)
    nums.sort()
    
    ans = []
    for i in range(n - 1):
        if nums[i] == nums[i + 1]:
            ans.append(nums[i])
    return ans
    
