#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 13 20:37:59 2017

@author: evelyn
"""

'''
Given a binary array, find the maximum number of consecutive 1s in this array.

Example 1:

Input: [1,1,0,1,1,1]
Output: 3
Explanation: The first two digits or the last three digits are consecutive 1s.
    The maximum number of consecutive 1s is 3.

Note:

    The input array will only contain 0 and 1.
    The length of input array is a positive integer and will not exceed 
    10,000

'''
def findMaxConsecutiveOnes(nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    maxNum = 0
    n = len(nums)
    i = 0
    tmp = 0
    
    while i <= n - 1:
        if nums[i] == 1:
           tmp += 1
           if tmp > maxNum:
               maxNum = tmp
        else:
           tmp = 0
        
        i += 1
        
    return maxNum
        
