#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 11 17:48:32 2017

@author: evelyn
"""

'''
 Find the contiguous subarray within an array (containing at least 
 one number) which has the largest sum.

For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6. 
'''
def maxSubArray(nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    n = len(nums)
    
    curSum = nums[0]
    maxSum = nums[0]
    
    for i in range(1, n):
        curSum = max(nums[i], curSum + nums[i])
        maxSum = max(maxSum, curSum)
    
    return maxSum
