#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 17 21:41:00 2017

@author: evelyn
"""

'''
Given an integer array, find three numbers whose product is maximum and output the 
maximum product.

Example 1:

Input: [1,2,3]
Output: 6

Example 2:

Input: [1,2,3,4]
Output: 24

Note:

    The length of the given array will be in range [3,104] and all elements are in the 
    range [-1000, 1000].
    Multiplication of any three numbers in the input won't exceed the range of 32-bit 
    signed integer.

'''
def maximumProduct(nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    pNum = [0]*3
    nNum = [0]*3
    for i in nums:
        if i < max(nNum):
            nNum[:] = [i] + sorted(nNum)[:2]
        elif i > min(pNum):
            pNum[:] = [i] + sorted(pNum)[1:]

    if len(nums) == 3:
        return nums[0]*nums[1]*nums[2]
    elif sum(pNum) == 0:
        return nNum[0] * nNum[1] * nNum[2]
    elif sorted(nNum)[0] * sorted(nNum)[1] > sorted(pNum)[0]*sorted(pNum)[1]:
        return sorted(nNum)[0] * sorted(nNum)[1] * max(pNum)
    else:
        return pNum[0] * pNum[1] * pNum[2]
