#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 12 12:13:05 2017

@author: evelyn
"""

'''
Given a non-negative integer represented as a non-empty array of digits, 
plus one to the integer.

You may assume the integer do not contain any leading zero, except the 
number 0 itself.

The digits are stored such that the most significant digit is at the 
head of the list.
'''
def plusOne(digits):
    """
    :type digits: List[int]
    :rtype: List[int]
    """
    n = len(digits)
    if n == 0:
        return [1]
    
    allSum = 0
    for i in range(n):
        allSum = allSum + digits[i] * pow(10, n-1-i)
    
    return [int(i) for i in str(allSum + 1)]
