#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 13 11:37:43 2017

@author: evelyn
"""

'''
Given two sorted integer arrays nums1 and nums2, merge nums2 into nums1 as 
one sorted array.

Note:
You may assume that nums1 has enough space (size that is greater or equal 
to m + n) to hold additional elements from nums2. The number of elements 
initialized in nums1 and nums2 are m and n respectively.
'''

def merge(nums1, m, nums2, n):
    """
    :type nums1: List[int]
    :type m: int
    :type nums2: List[int]
    :type n: int
    :rtype: void Do not return anything, modify nums1 in-place instead.
    """
    cur1 = m
    cur2 = n
    
    while cur1 > 0 and cur2 > 0:
        if nums1[cur1 - 1] >= nums2[cur2 - 1]:
            nums1[cur1+cur2-1] = nums1[cur1 - 1]
            cur1 -= 1
        else:
            nums1[cur1+cur2-1] = nums2[cur2 - 1]
            cur2 -= 1
    
    if cur2 > 0:
        nums1[:cur2] = nums2[:cur2]
        
    
