#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  3 23:39:23 2017

@author: evelyn
"""

'''
 Given n non-negative integers representing an elevation map where the width of each bar is 1, 
 compute how much water it is able to trap after raining.

For example,
Given [0,1,0,2,1,0,1,3,2,1,2,1], return 6. 
'''
def trap(height):
    """
    :type height: List[int]
    :rtype: int
    """
    n = len(height)
    h, t, minHeight, water = 0,n-1,0,0
    
    while h < t:
        while h < t and height[h] <= minHeight:
            water += minHeight - height[h]
            h += 1
        
        while h < t and height[t] <= minHeight:
            water += minHeight - height[t]
            t -= 1
        
        minHeight = min(height[h], height[t])
    
    return water
