#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  1 12:57:34 2017

@author: evelyn
"""

'''
Given n non-negative integers a1, a2, ..., an, where each represents a point at coordinate 
(i, ai). n vertical lines are drawn such that the two endpoints of line i is at (i, ai) 
and (i, 0). Find two lines, which together with x-axis forms a container, such that the 
container contains the most water.

Note: You may not slant the container and n is at least 2. 
'''
def maxArea(height):
    """
    :type height: List[int]
    :rtype: int
    """
    n = len(height)
    ans = 0

    for i in range(n):
        for j in range(i+1, n):
            ans = max((j-i)* min(height[i],height[j]), ans)
    return ans
