#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 27 22:06:54 2017

@author: evelyn
"""

'''
A peak element is an element that is greater than its neighbors.

Given an input array where num[i] ≠ num[i+1], find a peak element and return its index.

The array may contain multiple peaks, in that case return the index to any one of the 
peaks is fine.

You may imagine that num[-1] = num[n] = -∞.

For example, in array [1, 2, 3, 1], 3 is a peak element and your function should return 
the index number 2.

click to show spoilers.
Note:

Your solution should be in logarithmic complexity.

'''
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        if len(nums) == 1:
            return 0
        if len(nums) == 2:
            return 0 if nums[0] > nums[1] else 1

        for i in range(1,len(nums) - 1):
            if nums[i] > nums[i-1] and nums[i] > nums[i+1]:
                return i
        if nums[-1] > nums[-2]:
            return len(nums)-1
        
        
        
