#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 25 19:41:09 2017

@author: evelyn
"""

'''
Given a matrix of m x n elements (m rows, n columns), return all elements of the 
matrix in spiral order.

For example,
Given the following matrix:

[
 [ 1, 2, 3 ],
 [ 4, 5, 6 ],
 [ 7, 8, 9 ]
]

You should return [1,2,3,6,9,8,7,4,5]. 
'''
def spiralOrder(matrix):
    """
    :type matrix: List[List[int]]
    :rtype: List[int]
    """
    m = len(matrix)
    n = len(matrix[0])
    ans = []
    
    i = 0
    
    while i < m:
        ans.extend(matrix[i])
        # add last column to the ans
        for j in range(i+1,m):
            ans.extend(matrix[j][-1])
        ans.append(matrix[-1][-2::-1])

        for j in range(m-2, i, -1):
            ans.extend(matrix[j][0])
    
    return ans
        
