#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 25 19:41:09 2017

@author: evelyn
"""

'''
Given a matrix of m x n elements (m rows, n columns), return all elements of the 
matrix in spiral order.

For example,
Given the following matrix:

[
 [ 1, 2, 3 ],
 [ 4, 5, 6 ],
 [ 7, 8, 9 ]
]

You should return [1,2,3,6,9,8,7,4,5]. 
'''
def spiralOrder(matrix):
    """
    :type matrix: List[List[int]]
    :rtype: List[int]
    """
    ans = []
    while matrix:
        ans += matrix.pop(0)
                
        if matrix and matrix[0]:
            for row in matrix:
                ans.append(row.pop())
            
        if matrix:
            ans += matrix.pop()[::-1]
        
        if matrix and matrix[0]:
            for row in matrix[::-1]:
                ans.append(row.pop(0))
    
    return ans
        
