#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 14 11:53:32 2017

@author: evelyn
"""

'''
 Given two integers n and k, you need to construct a list which contains n 
 different positive integers ranging from 1 to n and obeys the following 
 requirement:
Suppose this list is [a1, a2, a3, ... , an], then the list [|a1 - a2|, 
|a2 - a3|, |a3 - a4|, ... , |an-1 - an|] has exactly k distinct integers.

If there are multiple answers, print any of them. 
'''
def constructArray(n, k):
    """
    :type n: int
    :type k: int
    :rtype: List[int]
    """
    ans = []

    ans[:] = list(range(1, n+1))

    i = 0
    while i <= k/2:
        ans.insert(n-k+2*i, ans[n-1])
        i += 1
    return ans[:n]
        
