#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 26 23:15:47 2017

@author: evelyn
"""

'''
 Given a non-negative integer, you could swap two digits at most once to get the 
 maximum valued number. Return the maximum valued number you could get.

Example 1:

Input: 2736
Output: 7236
Explanation: Swap the number 2 and the number 7.

Example 2:

Input: 9973
Output: 9973
Explanation: No swap.

Note:

    The given number is in the range [0, 10e-8]

'''
def maximumSwap(num):
    """
    :type num: int
    :rtype: int
    """
    
    dig = map(int, str(num))

    dic = {x:i for i,x in enumerate(dig)}
    for i, x in enumerate(dig):
        for y in range(9, x, -1):
            if dic.get(y,None) > i:
                dig[i], dig[dic[y]] = y, dig[i]
                return int("".join(map(str, dig)))
    return num
