#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 26 23:15:47 2017

@author: evelyn
"""

'''
 Given a non-negative integer, you could swap two digits at most once to get the 
 maximum valued number. Return the maximum valued number you could get.

Example 1:

Input: 2736
Output: 7236
Explanation: Swap the number 2 and the number 7.

Example 2:

Input: 9973
Output: 9973
Explanation: No swap.

Note:

    The given number is in the range [0, 10e-8]

'''
def maximumSwap(num):
    """
    :type num: int
    :rtype: int
    """
    
    dig = list(str(num))
    for i in range(len(dig)):
        dig[i] = int(dig[i])

    maxDig = dig[0]
    idx = 0
    for i in range(1, len(dig)):
        if dig[i] > maxDig:
            maxDig = dig[i]
            idx = i

    dig[0],dig[idx] = dig[idx],dig[0]

    ans = ""
    for item in dig:
        ans += str(item)

    return int(ans)
