#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 26 23:15:47 2017

@author: evelyn
"""

'''
 Given a non-negative integer, you could swap two digits at most once to get the 
 maximum valued number. Return the maximum valued number you could get.

Example 1:

Input: 2736
Output: 7236
Explanation: Swap the number 2 and the number 7.

Example 2:

Input: 9973
Output: 9973
Explanation: No swap.

Note:

    The given number is in the range [0, 10e-8]

'''
def maximumSwap(num):
    """
    :type num: int
    :rtype: int
    """
    
    dig = list(str(num))
    for i in range(len(dig)):
        dig[i] = int(dig[i])
    
   # cur = dig[0]
    dic = {dig[0]:0}
    for i in range(1, len(dig)):
        print "i = "+ str(i)
        if dig[i] <= dig[i-1]:
            dic[dig[i]] = i
        else:
            idx = dic[max([x for x in dic.keys() if x < dig[i]])]
            print "idx = "+ str(idx)
            dig[i], dig[idx] = dig[idx],dig[i]
            print "dig = "+ str(dig)
            break
    
    ans = ""
    for item in dig:
        ans += str(item)
    
    return int(ans)
