#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 28 23:05:08 2017

@author: evelyn
"""

'''
 Given a collection of integers that might contain duplicates, nums, return all possible subsets.

Note: The solution set must not contain duplicate subsets.

For example,
If nums = [1,2,2], a solution is:

[
  [2],
  [1],
  [1,2,2],
  [2,2],
  [1,2],
  []
]
'''
def subsetsWithDup(nums):
    """
    :type nums: List[int]
    :rtype: List[List[int]]
    """
    ans = [[]]
    for item in nums:
        cur = [j + [item] for j in ans]
        for i in cur:
            if sorted(i) not in ans:
                ans += [sorted(i)]
    return ans
